### ISSUE TITLE
下载 apk 结束后还需要对文件进行校验

### ISSUE THREAD

**Issue by lytsing** [LyndonChin/ZanAppUpdater#2]
没有对 apk 包进行校验，这个是有安全隐患的。应该从服务器上获取文件的 fileSize 与 MD5 值，先校验 fileSize，再校验 MD5，两者都 OK 才算是下载成功。

**Comment by liangfeidotme** [comment]
* 如果是 https 请求，除了中间人攻击，内容被篡改或窃听的可能性很低（因为 payload 都加密了）
* 如果是 http 请求，需要校验摘要的话，MD5（最好是SHA256）值能够保证数据完整性，不需要 fileSize
* 再高一个级别的话可以做服务端签名校验

**Comment by liangfeidotme** [comment]
其实，我做这个项目的初衷是为了充分利用 Android 提供的系统能力，直接用 DownloadManager 去下载文件，而不是自己去实现一套 http 请求。
